version: '2'

services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - portal-network
    depends_on:
      - mongodb


  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - portal-network

  dialogflowproxy:
    build:
      context: ../sup-dialogflow-proxy
      dockerfile: $PWD/../sup-dialogflow-proxy/Dockerfile
    ports:
      - 9000:9000
    networks:
      - portal-network
    depends_on:
      - node


networks:
  portal-network:
    driver: bridge